name: 00 - Main CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
  
permissions:
  actions: read
  contents: read
  security-events: write
  checks: write
  issues: read
  pull-requests: write
  
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit

  sast:
    needs: build
    name: SAST
    uses: ./.github/workflows/sast.yml
    secrets: inherit

  docker:
    needs: build
    name: Build docker image
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  container-image-scan:
    needs: docker
    name: Scan docker image
    uses: ./.github/workflows/container-image-scan.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.docker.outputs.image-tag }}
 
